<a href="https://colab.research.google.com/github/zoelzw/python-practice/blob/master/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW1 Scripts


In [4]:
import numpy as np
from IPython.display import display, Math, HTML
import pandas as pd

## Q1 e



### part b 

In [13]:
x = np.array([[1,1,0,0],[1,1,0,0],[0,1,2,1],[0,1,0,1],[0,0,3,1]])
c = np.array([2,1,3,6,8])
print("c@x = %s \n" % (c@x)) 
display(Math(rf'c^\top x = '), c@x)



c@x = [ 3 12 30 17] 



<IPython.core.display.Math object>

array([ 3, 12, 30, 17])

### part c


In [ ]:
z = [1,2,3]

print("x/4 = ",x/4)
print("z/4 = ",z/4)  # this results in an error

x/4 =  [0.25 0.5  0.75]


TypeError: unsupported operand type(s) for /: 'list' and 'int'

## compute an inner (dot) product

In [ ]:
z = np.array([4,5,6])
p = np.dot(x,z)
p2 = x*z
p3 = x@z

print("x^T z = ", p)
print("np.dot(x,z) = %s, x*z = %s, x@z = %s" % (p,p2,p3))
display(Math(rf'x^\top z = ({x[0]}\times {z[0]}) + ({x[1]}\times {z[1]}) + ({x[2]}\times {z[2]}) = {p}'))

print("x z^T = ",np.outer(x,z))

x^T z =  32
np.dot(x,z) = 32, x*z = [ 4 10 18], x@z = 32


<IPython.core.display.Math object>

x z^T =  [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## matrices

In [ ]:
A = np.array([[1, 1, 0, 0, 0],[0, 1, 2, 0, 3],[0, 5, 0, 6, 0]])

print("A =",A)
print("A = ",pd.DataFrame(A))
print("A =\n",pd.DataFrame(A))
print("A = ",pd.DataFrame(A).to_string(index=False,header=False))

HTML(pd.DataFrame(A).to_html(index=False,header=False))


A = [[1 1 0 0 0]
 [0 1 2 0 3]
 [0 5 0 6 0]]
A =     0  1  2  3  4
0  1  1  0  0  0
1  0  1  2  0  3
2  0  5  0  6  0
A =
    0  1  2  3  4
0  1  1  0  0  0
1  0  1  2  0  3
2  0  5  0  6  0
A =   1  1  0  0  0
 0  1  2  0  3
 0  5  0  6  0


## matrix-vector products

In [ ]:
print("x@A = %s" % (x@A))
display(Math(rf'x^\top A = '),x@A)

print("A@y = %s" % (A@y))
display(Math(rf'Ay = '),A@y)

print("x@A@y = %s" % (x@A@y))
display(Math(rf'x^\top Ay = '),x@A@y)



x@A = [ 1 18  4 18  6]


<IPython.core.display.Math object>

array([ 1, 18,  4, 18,  6])

A@y = [ 6 46 68]


<IPython.core.display.Math object>

array([ 6, 46, 68])

x@A@y = 302


<IPython.core.display.Math object>

302

In [ ]:
print("A = ",A)
print("1st row of A = [1, 0, 0]@A = ",np.array([1, 0, 0])@A )
print("2nd row of A = [0, 1, 0]@A = ",np.array([0, 1, 0])@A )
print("3rd row of A = [0, 0, 1]@A = ",np.array([0, 0, 1])@A )
print("2x 1st row + 3rd row of A = [2, 0, 1]@A = ",np.array([2, 0, 1])@A)

A =  [[1 1 0 0 0]
 [0 1 2 0 3]
 [0 5 0 6 0]]
1st row of A = [1, 0, 0]@A =  [1 1 0 0 0]
2nd row of A = [0, 1, 0]@A =  [0 1 2 0 3]
3rd row of A = [0, 0, 1]@A =  [0 5 0 6 0]
2x 1st row + 3rd row of A = [2, 0, 1]@A =  [2 7 0 6 0]


In [ ]:
print("A = \n",A)
print("1st col of A = A@[1,0,0,0,0] = ",A@np.array([1,0,0,0,0]) )
print("2nd col of A = A@[0,1,0,0,0] = ",A@np.array([0,1,0,0,0]) )
print("3rd col of A = A@[0,0,1,0,0] = ",A@np.array([0,0,1,0,0]) )
print("4th col of A = A@[0,0,0,1,0] = ",A@np.array([0,0,0,1,0]) )
print("5th col of A = A@[0,0,0,0,1] = ",A@np.array([0,0,0,0,1]) )

print("2x 1st col + 4th col = A@[2,0,0,1,0] = ",A@np.array([2,0,0,1,0]))

A = 
 [[1 1 0 0 0]
 [0 1 2 0 3]
 [0 5 0 6 0]]
1st col of A = A@[1,0,0,0,0] =  [1 0 0]
2nd col of A = A@[0,1,0,0,0] =  [1 1 5]
3rd col of A = A@[0,0,1,0,0] =  [0 2 0]
4th col of A = A@[0,0,0,1,0] =  [0 0 6]
5th col of A = A@[0,0,0,0,1] =  [0 3 0]
2x 1st col + 4th col = A@[2,0,0,1,0] =  [2 0 6]
